Update packaging with new checksum strategy
Our previous strategy of copying a fake checksum file to the problematic
crate was unsustainable, since dependencies can change (either directly
or indirectly) when updating our code (or our dependencies version) and
new crates with .a files could emerge.

To fix this, a script was created to parse each vendored dep changelog
to see if there's any .a file listed and, if so, replaces the dep
changelog with a more generic one, using only the general crate checksum
instead of the default per-file one.

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -32,12 +32,24 @@ override_dh_auto_clean:
 	# Create the vendor directory when building the source package
 	[ -d vendor/ ] || go mod vendor
 
-	# vcpkg has the same issue as system-deps, with .a files that are trimmed by dpkg-source.
-	# so we need to replace the crate checksum to avoid build errors.
+	# Some crates are shipped with .a files, which get removed by the helpers during the package build as a safety measure.
+	# This results in cargo failing to compile, since the files (which are listed in the checksums) are not there anymore.
+	# For those crates, we need to replace their checksum with a more general one that only lists the crate checksum, instead of each file.
 	if [ ! -d $(CARGO_VENDOR_DIR)/ ]; then \
 		$(CARGO) vendor $(CARGO_VENDOR_DIR); \
-		cp debian/cargo-checksum.json $(CARGO_VENDOR_DIR)/vcpkg/.cargo-checksum.json; \
 		[ ! -e $(DH_CARGO_VENDORED_SOURCES) ] || $(DH_CARGO_VENDORED_SOURCES); \
+		\
+		[ -e /usr/bin/jq ] || (echo "jq is required to run this script. Try installing it with 'sudo apt install jq'" && exit 1); \
+		\
+		for dep in $$(ls vendor_rust -1); do \
+			checksum_file="vendor_rust/$${dep}/.cargo-checksum.json"; \
+			a_files=$$(cat $${checksum_file} | jq '.files | keys | map(select(.|test(".a$$")))'); \
+			if [ "$$a_files" = "[]" ]; then \
+				continue; \
+			fi; \
+			pkg_checksum=$$(cat "$${checksum_file}" | jq '.package'); \
+			echo "{\"files\": {}, \"package\": $${pkg_checksum}}" >"$${checksum_file}"; \
+		done; \
 	fi
 
 override_dh_auto_configure:
